/// Agent Executors
///
/// Pluggable execution engines for agents.
/// Currently implements Mock executor for testing.
use crate::agent_backend::agent_card::{AgentCard, CognitionTier};
use crate::ast::{AgentStmt, EvidenceStmt, Program};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Execution context passed to executors
#[derive(Debug, Clone)]
pub struct ExecutionContext {
    pub program: Program,
    pub agent_card: AgentCard,
    /// Creature ID executing this agent (None for non-creature executions)
    pub creature_id: Option<Uuid>,
    /// Creature's cognition tier — drives model ladder resolution (None = use card defaults)
    pub cognition_tier: Option<CognitionTier>,
}

/// A record of a single tool invocation during agentic execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolInvocation {
    pub tool_name: String,
    pub input: serde_json::Value,
    pub output: String,
    pub duration_ms: u64,
    pub iteration: u32,
}

/// Agent execution output
#[derive(Debug, Clone)]
pub struct AgentOutput {
    pub agent_name: String,
    pub agent_type: String,
    pub timestamp: DateTime<Utc>,
    pub status: AgentStatus,
    pub evidence: Vec<EvidenceStmt>,
    pub confidence: f64,
    pub sources_consulted: Vec<String>,
    pub execution_time_ms: u64,
    pub tokens_used: Option<u32>,
    pub metadata: AgentMetadata,
    /// Tool invocations performed during agentic loop (empty for single-turn)
    pub tool_invocations: Vec<ToolInvocation>,
    /// Number of LLM round-trips (1 for single-turn, >1 for tool-using agents)
    pub loop_iterations: u32,
}

/// Agent execution status
#[derive(Debug, Clone, PartialEq)]
pub enum AgentStatus {
    Success,
    Failed,
    Timeout,
    BelowConfidenceThreshold,
}

/// Agent execution metadata
#[derive(Debug, Clone, Default)]
pub struct AgentMetadata {
    pub model_used: Option<String>,
    pub temperature: Option<f64>,
    pub reasoning: Option<String>,
    /// Provider that handled the request (anthropic, openai, openrouter, …) —
    /// resolved at execution time, not just whatever the card declared.
    pub provider: Option<String>,
    /// Final stop / finish reason reported by the LLM
    /// (anthropic: stop / tool_use / max_tokens / end_turn / pause_turn / refusal;
    ///  openai-compatible: stop / tool_calls / length / content_filter / function_call).
    /// Critical for diagnosing tool-loop exits and silent truncations
    /// (see issue #3 / docs/specs/10_RESEARCH_AGENTS_EMPTY_LLM_OUTPUT.md).
    pub stop_reason: Option<String>,
    /// If the executor decided this run did not actually succeed
    /// (e.g. empty content after consuming tokens, tool-loop cap-out without
    /// final text), a short machine-readable reason string. None = no failure.
    pub failure_reason: Option<String>,
    /// Doc 12 § Capability 2 — agent version at execution time. Populated
    /// by the caller (workspace message handler, execution endpoint) after
    /// the executor returns, by resolving `MAX(version_number)` from
    /// `agent_versions` for this agent. Executors themselves leave these
    /// as `None`.
    pub agent_version_id: Option<uuid::Uuid>,
    pub agent_version_number: Option<i32>,
}

/// Execution error
#[derive(Debug, Clone)]
pub enum ExecutionError {
    ExecutorNotFound(String),
    ExecutionFailed(String),
    InvalidContext(String),
    Timeout,
}

impl std::fmt::Display for ExecutionError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            ExecutionError::ExecutorNotFound(s) => write!(f, "Executor not found: {}", s),
            ExecutionError::ExecutionFailed(s) => write!(f, "Execution failed: {}", s),
            ExecutionError::InvalidContext(s) => write!(f, "Invalid context: {}", s),
            ExecutionError::Timeout => write!(f, "Execution timeout"),
        }
    }
}

impl std::error::Error for ExecutionError {}

/// Agent executor trait
#[async_trait::async_trait]
pub trait AgentExecutor: Send + Sync {
    /// Execute the agent with given context
    async fn execute(
        &self,
        agent: &AgentStmt,
        context: &ExecutionContext,
    ) -> Result<AgentOutput, ExecutionError>;

    /// Name of this executor
    fn name(&self) -> &str;
}

/// Mock executor for testing
pub struct MockExecutor;

impl MockExecutor {
    pub fn new() -> Self {
        MockExecutor
    }
}

#[async_trait::async_trait]
impl AgentExecutor for MockExecutor {
    async fn execute(
        &self,
        agent: &AgentStmt,
        _context: &ExecutionContext,
    ) -> Result<AgentOutput, ExecutionError> {
        use std::time::Instant;
        let start = Instant::now();

        // Generate mock evidence
        let evidence = EvidenceStmt {
            id: format!("{}_evidence_mock", agent.name),
            source: "Mock Executor".to_string(),
            summary: Some("Generated by mock executor for testing purposes".to_string()),
            url: None,
            relevance: Some(0.75),
            date: Some(Utc::now().format("%Y-%m-%d").to_string()),
            strength: Some(0.75),
            key_findings: vec![
                format!("Mock finding 1 for agent '{}'", agent.name),
                format!("Mock finding 2 based on query: {}", agent.query),
                "This is simulated evidence for testing".to_string(),
            ],
        };

        let elapsed = start.elapsed();

        Ok(AgentOutput {
            agent_name: agent.name.clone(),
            agent_type: agent.agent_type.clone().unwrap_or_default(),
            timestamp: Utc::now(),
            status: AgentStatus::Success,
            evidence: vec![evidence],
            confidence: 0.75,
            sources_consulted: vec!["mock://test".to_string()],
            execution_time_ms: elapsed.as_millis() as u64,
            tokens_used: Some(100), // Mock token count
            metadata: AgentMetadata {
                model_used: Some("mock-model".to_string()),
                temperature: Some(0.0),
                reasoning: Some("Mock execution for testing".to_string()),
                ..Default::default()
            },
            tool_invocations: vec![],
            loop_iterations: 1,
        })
    }

    fn name(&self) -> &str {
        "mock"
    }
}

impl Default for MockExecutor {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{AgentStmt, Schedule, TimeUnit};

    #[tokio::test]
    async fn test_mock_executor() {
        let agent = AgentStmt {
            name: "test_agent".to_string(),
            agent_type: Some("research".to_string()),
            query: "Test query".to_string(),
            executor: None,
            schedule: Some(Schedule::Every {
                interval: 1,
                unit: TimeUnit::Day,
            }),
            driver_refs: vec![],
            depends_on: vec![],
            confidence_threshold: None,
        };

        let program = Program { statements: vec![] };
        let card =
            crate::agent_backend::AgentCard::new("test_agent".to_string(), "research".to_string());

        let context = ExecutionContext {
            program,
            agent_card: card,
            creature_id: None,
            cognition_tier: None,
        };

        let executor = MockExecutor::new();
        let result = executor.execute(&agent, &context).await;

        assert!(result.is_ok());
        let output = result.unwrap();
        assert_eq!(output.agent_name, "test_agent");
        assert_eq!(output.status, AgentStatus::Success);
        assert_eq!(output.evidence.len(), 1);
        assert_eq!(output.confidence, 0.75);
    }

    /// Pins the optional fields (issue #3 + issue #5) so older constructors
    /// that don't set them keep compiling via `..Default::default()`.
    #[test]
    fn agent_metadata_default_has_none_observability_fields() {
        let m = AgentMetadata::default();
        assert!(m.model_used.is_none());
        assert!(m.temperature.is_none());
        assert!(m.reasoning.is_none());
        assert!(m.provider.is_none());
        assert!(m.stop_reason.is_none());
        assert!(m.failure_reason.is_none());
        // Doc 12 § Capability 2 — version stamp fields default to None.
        assert!(m.agent_version_id.is_none());
        assert!(m.agent_version_number.is_none());
    }
}
