<script lang="ts">
  /**
   * Question Cell Component
   *
   * Displays and edits a forecasting question with base rate.
   * Modular, self-contained, strictly typed.
   */

  import type { QuestionCell as QuestionCellType } from '../../types/notebook';
  import { updateCell, executeSingleCell } from '../../stores/notebook';

  export let cell: QuestionCellType;
  export let readonly: boolean = false;

  let isEditing = false;
  let editedText = cell.text;

  function handleSave() {
    updateCell(cell.id, { text: editedText });
    isEditing = false;
  }

  function handleCancel() {
    editedText = cell.text;
    isEditing = false;
  }

  function handleExecute() {
    executeSingleCell(cell.id);
  }
</script>

<div class="cell question-cell">
  <!-- Cell Toolbar -->
  <div class="cell-toolbar">
    <span class="cell-type">Question</span>
    <div class="cell-actions">
      {#if !readonly}
        {#if isEditing}
          <button on:click={handleSave} class="btn-small">Save</button>
          <button on:click={handleCancel} class="btn-small">Cancel</button>
        {:else}
          <button on:click={() => (isEditing = true)} class="btn-small">Edit</button>
          <button on:click={handleExecute} class="btn-small btn-primary">Run</button>
        {/if}
      {/if}
    </div>
  </div>

  <!-- Question Text -->
  <div class="cell-content">
    {#if isEditing}
      <textarea
        bind:value={editedText}
        class="question-input"
        placeholder="Enter your forecasting question..."
        rows="3"
      />
    {:else}
      <div class="question-text">
        {#if cell.text}
          {cell.text}
        {:else}
          <em>No question specified</em>
        {/if}
      </div>
    {/if}
  </div>

  <!-- Output (Probability) -->
  {#if cell.output}
    <div class="cell-output">
      <div class="probability-result">
        <span class="label">P(Yes) =</span>
        <span class="value">{(cell.output.probability * 100).toFixed(1)}%</span>
      </div>

      {#if cell.output.confidence_interval}
        <div class="confidence-interval">
          <span class="label">95% CI:</span>
          <span class="range">
            [{(cell.output.confidence_interval[0] * 100).toFixed(1)}%,
            {(cell.output.confidence_interval[1] * 100).toFixed(1)}%]
          </span>
        </div>
      {/if}

      {#if cell.output.brier_score !== undefined}
        <div class="brier-score">
          <span class="label">Brier:</span>
          <span class="value">{cell.output.brier_score.toFixed(3)}</span>
        </div>
      {/if}
    </div>
  {/if}

  <!-- Base Rate (if present) -->
  {#if cell.base_rate}
    <details class="base-rate-details">
      <summary>Base Rate: {(cell.base_rate.historical_frequency * 100).toFixed(1)}%</summary>
      <div class="base-rate-content">
        <div class="field">
          <strong>Reference Class:</strong>
          <p>{cell.base_rate.reference_class}</p>
        </div>
        <div class="field">
          <strong>Sample Size:</strong>
          <p>{cell.base_rate.sample_size}</p>
        </div>
        <div class="field">
          <strong>Source:</strong>
          <p>{cell.base_rate.source}</p>
        </div>
        <div class="field">
          <strong>Reasoning:</strong>
          <p>{cell.base_rate.reasoning}</p>
        </div>
        <div class="field">
          <strong>Generated By:</strong>
          <span class="badge">{cell.base_rate.generated_by}</span>
        </div>
      </div>
    </details>
  {/if}
</div>

<style>
  /* Gruvbox colors */
  .cell {
    background: #3c3836;
    border: 1px solid #504945;
    border-radius: 6px;
    padding: 16px;
    margin-bottom: 12px;
  }

  .cell-toolbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 12px;
    padding-bottom: 8px;
    border-bottom: 1px solid #504945;
  }

  .cell-type {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: #bdae93;
    font-weight: 500;
  }

  .cell-actions {
    display: flex;
    gap: 8px;
  }

  .btn-small {
    padding: 4px 12px;
    font-size: 12px;
    background: transparent;
    border: 1px solid #665c54;
    color: #ebdbb2;
    border-radius: 4px;
    cursor: pointer;
    font-weight: 400;
  }

  .btn-small:hover {
    background: #504945;
  }

  .btn-primary {
    background: #8ec07c;
    border-color: #8ec07c;
    color: #1d2021;
  }

  .btn-primary:hover {
    background: #b8bb26;
    border-color: #b8bb26;
  }

  .cell-content {
    margin-bottom: 12px;
  }

  .question-input {
    width: 100%;
    background: #282828;
    border: 1px solid #665c54;
    color: #ebdbb2;
    padding: 12px;
    font-size: 14px;
    font-family: inherit;
    border-radius: 4px;
    resize: vertical;
  }

  .question-input:focus {
    outline: none;
    border-color: #8ec07c;
  }

  .question-text {
    font-size: 16px;
    color: #fbf1c7;
    line-height: 1.5;
    font-weight: 400;
  }

  .cell-output {
    background: #282828;
    padding: 12px;
    border-radius: 4px;
    display: flex;
    gap: 24px;
    align-items: center;
  }

  .probability-result {
    display: flex;
    align-items: baseline;
    gap: 8px;
  }

  .probability-result .label {
    font-size: 12px;
    color: #bdae93;
  }

  .probability-result .value {
    font-size: 24px;
    font-weight: 300;
    color: #8ec07c;
  }

  .confidence-interval,
  .brier-score {
    display: flex;
    align-items: baseline;
    gap: 6px;
    font-size: 12px;
  }

  .confidence-interval .label,
  .brier-score .label {
    color: #928374;
  }

  .confidence-interval .range,
  .brier-score .value {
    color: #d5c4a1;
  }

  .base-rate-details {
    margin-top: 12px;
    padding-top: 12px;
    border-top: 1px solid #504945;
  }

  .base-rate-details summary {
    font-size: 13px;
    color: #fe8019;
    cursor: pointer;
    font-weight: 500;
  }

  .base-rate-content {
    margin-top: 12px;
    padding-left: 16px;
  }

  .field {
    margin-bottom: 8px;
    font-size: 13px;
  }

  .field strong {
    display: block;
    color: #bdae93;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-bottom: 4px;
  }

  .field p {
    color: #d5c4a1;
    margin: 0;
    line-height: 1.5;
  }

  .badge {
    display: inline-block;
    padding: 2px 8px;
    background: #504945;
    color: #ebdbb2;
    border-radius: 3px;
    font-size: 11px;
  }
</style>
