#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 23
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 17

enum ts_symbol_identifiers {
  anon_sym_forecast = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_driver = 4,
  anon_sym_estimate = 5,
  anon_sym_triangular = 6,
  anon_sym_LPAREN = 7,
  anon_sym_COMMA = 8,
  anon_sym_RPAREN = 9,
  anon_sym_normal = 10,
  anon_sym_lognormal = 11,
  anon_sym_uniform = 12,
  anon_sym_beta = 13,
  anon_sym_STAR = 14,
  anon_sym_SLASH = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_CARET = 18,
  anon_sym_BANG = 19,
  sym_identifier = 20,
  sym_number = 21,
  aux_sym_probability_token1 = 22,
  aux_sym_probability_token2 = 23,
  anon_sym_DQUOTE = 24,
  aux_sym_string_token1 = 25,
  anon_sym_BSLASH = 26,
  aux_sym_string_token2 = 27,
  sym_comment = 28,
  sym_source_file = 29,
  sym__statement = 30,
  sym_forecast_statement = 31,
  sym_block = 32,
  sym_driver_statement = 33,
  sym_estimate_statement = 34,
  sym_distribution = 35,
  sym_triangular_distribution = 36,
  sym_normal_distribution = 37,
  sym_lognormal_distribution = 38,
  sym_uniform_distribution = 39,
  sym_beta_distribution = 40,
  sym_expression = 41,
  sym_binary_expression = 42,
  sym_unary_expression = 43,
  sym_function_call = 44,
  sym_parenthesized_expression = 45,
  sym_probability = 46,
  sym_string = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_function_call_repeat1 = 49,
  aux_sym_string_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_forecast] = "forecast",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_driver] = "driver",
  [anon_sym_estimate] = "estimate",
  [anon_sym_triangular] = "triangular",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_normal] = "normal",
  [anon_sym_lognormal] = "lognormal",
  [anon_sym_uniform] = "uniform",
  [anon_sym_beta] = "beta",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_CARET] = "^",
  [anon_sym_BANG] = "!",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [aux_sym_probability_token1] = "probability_token1",
  [aux_sym_probability_token2] = "probability_token2",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_string_token2] = "string_token2",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_forecast_statement] = "forecast_statement",
  [sym_block] = "block",
  [sym_driver_statement] = "driver_statement",
  [sym_estimate_statement] = "estimate_statement",
  [sym_distribution] = "distribution",
  [sym_triangular_distribution] = "triangular_distribution",
  [sym_normal_distribution] = "normal_distribution",
  [sym_lognormal_distribution] = "lognormal_distribution",
  [sym_uniform_distribution] = "uniform_distribution",
  [sym_beta_distribution] = "beta_distribution",
  [sym_expression] = "expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_function_call] = "function_call",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_probability] = "probability",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_forecast] = anon_sym_forecast,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_driver] = anon_sym_driver,
  [anon_sym_estimate] = anon_sym_estimate,
  [anon_sym_triangular] = anon_sym_triangular,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_normal] = anon_sym_normal,
  [anon_sym_lognormal] = anon_sym_lognormal,
  [anon_sym_uniform] = anon_sym_uniform,
  [anon_sym_beta] = anon_sym_beta,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [aux_sym_probability_token1] = aux_sym_probability_token1,
  [aux_sym_probability_token2] = aux_sym_probability_token2,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_forecast_statement] = sym_forecast_statement,
  [sym_block] = sym_block,
  [sym_driver_statement] = sym_driver_statement,
  [sym_estimate_statement] = sym_estimate_statement,
  [sym_distribution] = sym_distribution,
  [sym_triangular_distribution] = sym_triangular_distribution,
  [sym_normal_distribution] = sym_normal_distribution,
  [sym_lognormal_distribution] = sym_lognormal_distribution,
  [sym_uniform_distribution] = sym_uniform_distribution,
  [sym_beta_distribution] = sym_beta_distribution,
  [sym_expression] = sym_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_function_call] = sym_function_call,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_probability] = sym_probability,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_forecast] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_driver] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_estimate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_triangular] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_normal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lognormal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uniform] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_beta] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_probability_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_probability_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_forecast_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_driver_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_estimate_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_distribution] = {
    .visible = true,
    .named = true,
  },
  [sym_triangular_distribution] = {
    .visible = true,
    .named = true,
  },
  [sym_normal_distribution] = {
    .visible = true,
    .named = true,
  },
  [sym_lognormal_distribution] = {
    .visible = true,
    .named = true,
  },
  [sym_uniform_distribution] = {
    .visible = true,
    .named = true,
  },
  [sym_beta_distribution] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_probability] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alpha = 1,
  field_argument = 2,
  field_beta = 3,
  field_body = 4,
  field_distribution = 5,
  field_expression = 6,
  field_function = 7,
  field_high = 8,
  field_left = 9,
  field_low = 10,
  field_max = 11,
  field_mean = 12,
  field_median = 13,
  field_min = 14,
  field_name = 15,
  field_operand = 16,
  field_p5 = 17,
  field_p50 = 18,
  field_p95 = 19,
  field_right = 20,
  field_sigma = 21,
  field_stddev = 22,
  field_title = 23,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alpha] = "alpha",
  [field_argument] = "argument",
  [field_beta] = "beta",
  [field_body] = "body",
  [field_distribution] = "distribution",
  [field_expression] = "expression",
  [field_function] = "function",
  [field_high] = "high",
  [field_left] = "left",
  [field_low] = "low",
  [field_max] = "max",
  [field_mean] = "mean",
  [field_median] = "median",
  [field_min] = "min",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_p5] = "p5",
  [field_p50] = "p50",
  [field_p95] = "p95",
  [field_right] = "right",
  [field_sigma] = "sigma",
  [field_stddev] = "stddev",
  [field_title] = "title",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 3},
  [10] = {.index = 15, .length = 2},
  [11] = {.index = 17, .length = 2},
  [12] = {.index = 19, .length = 2},
  [13] = {.index = 21, .length = 2},
  [14] = {.index = 23, .length = 2},
  [15] = {.index = 25, .length = 3},
  [16] = {.index = 28, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_expression, 1},
  [1] =
    {field_body, 2},
    {field_title, 1},
  [3] =
    {field_distribution, 2},
    {field_name, 1},
  [5] =
    {field_operand, 1},
  [6] =
    {field_function, 0},
  [7] =
    {field_left, 0},
    {field_right, 2},
  [9] =
    {field_argument, 2},
    {field_function, 0},
  [11] =
    {field_argument, 1},
  [12] =
    {field_argument, 2},
    {field_argument, 3, .inherited = true},
    {field_function, 0},
  [15] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [17] =
    {field_mean, 2},
    {field_stddev, 4},
  [19] =
    {field_median, 2},
    {field_sigma, 4},
  [21] =
    {field_high, 4},
    {field_low, 2},
  [23] =
    {field_alpha, 2},
    {field_beta, 4},
  [25] =
    {field_p5, 2},
    {field_p50, 4},
    {field_p95, 6},
  [28] =
    {field_alpha, 2},
    {field_beta, 4},
    {field_max, 8},
    {field_min, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(59);
      ADVANCE_MAP(
        '!', 78,
        '"', 85,
        '(', 66,
        ')', 68,
        '*', 73,
        '+', 75,
        ',', 67,
        '-', 76,
        '/', 74,
        '\\', 89,
        '^', 77,
        'b', 15,
        'd', 41,
        'e', 49,
        'f', 37,
        'l', 36,
        'n', 38,
        'p', 57,
        't', 46,
        'u', 34,
        '{', 61,
        '}', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '/') ADVANCE(91);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(92);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(78);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(68);
      if (lookahead == '-') ADVANCE(76);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'p') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(85);
      if (lookahead == '/') ADVANCE(87);
      if (lookahead == '\\') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(94);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(93);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(72);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(50);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(55);
      END_STATE();
    case 21:
      if (lookahead == 'g') ADVANCE(35);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(56);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(70);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 29:
      if (lookahead == 'm') ADVANCE(71);
      END_STATE();
    case 30:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(10);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(54);
      END_STATE();
    case 50:
      if (lookahead == 's') ADVANCE(52);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 55:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 56:
      if (lookahead == 'v') ADVANCE(18);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_forecast);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_driver);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_estimate);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_triangular);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_normal);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_lognormal);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_uniform);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_beta);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(94);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(84);
      if (lookahead == '.') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_probability_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_probability_token2);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(94);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(87);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(86);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(94);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(91);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(90);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(94);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_forecast] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_driver] = ACTIONS(1),
    [anon_sym_estimate] = ACTIONS(1),
    [anon_sym_triangular] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_normal] = ACTIONS(1),
    [anon_sym_lognormal] = ACTIONS(1),
    [anon_sym_uniform] = ACTIONS(1),
    [anon_sym_beta] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_probability_token1] = ACTIONS(1),
    [aux_sym_probability_token2] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(82),
    [sym__statement] = STATE(39),
    [sym_forecast_statement] = STATE(39),
    [sym_driver_statement] = STATE(39),
    [sym_estimate_statement] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(39),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_forecast] = ACTIONS(7),
    [anon_sym_driver] = ACTIONS(9),
    [anon_sym_estimate] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(40), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [36] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(49), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [69] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(44), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [102] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(36), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [135] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(45), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [168] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(43), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [201] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(46), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [234] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(48), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [267] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(54), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [300] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(47), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [333] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(30), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [366] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(27), 11,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_CARET,
  [389] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(51), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [422] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(26), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [455] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(27), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [488] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(28), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [521] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(41), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [554] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(42), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [587] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(50), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [620] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(55), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [653] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(53), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [686] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_probability_token1,
    ACTIONS(25), 1,
      aux_sym_probability_token2,
    STATE(52), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 5,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call,
      sym_parenthesized_expression,
      sym_probability,
  [719] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(33), 11,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_CARET,
  [739] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(37), 11,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_CARET,
  [759] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(41), 8,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_CARET,
  [783] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(41), 10,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_CARET,
  [805] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_SLASH,
    ACTIONS(41), 11,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_CARET,
  [825] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_SLASH,
    ACTIONS(51), 11,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_CARET,
  [845] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_SLASH,
    ACTIONS(55), 11,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_CARET,
  [865] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_SLASH,
    ACTIONS(59), 11,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_CARET,
  [885] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(27), 11,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_CARET,
  [905] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    ACTIONS(63), 11,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_CARET,
  [925] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_triangular,
    ACTIONS(69), 1,
      anon_sym_normal,
    ACTIONS(71), 1,
      anon_sym_lognormal,
    ACTIONS(73), 1,
      anon_sym_uniform,
    ACTIONS(75), 1,
      anon_sym_beta,
    STATE(61), 1,
      sym_distribution,
    STATE(60), 5,
      sym_triangular_distribution,
      sym_normal_distribution,
      sym_lognormal_distribution,
      sym_uniform_distribution,
      sym_beta_distribution,
  [954] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_forecast,
    ACTIONS(82), 1,
      anon_sym_driver,
    ACTIONS(85), 1,
      anon_sym_estimate,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(35), 5,
      sym__statement,
      sym_forecast_statement,
      sym_driver_statement,
      sym_estimate_statement,
      aux_sym_source_file_repeat1,
  [978] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(88), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1002] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_forecast,
    ACTIONS(9), 1,
      anon_sym_driver,
    ACTIONS(11), 1,
      anon_sym_estimate,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    STATE(38), 5,
      sym__statement,
      sym_forecast_statement,
      sym_driver_statement,
      sym_estimate_statement,
      aux_sym_source_file_repeat1,
  [1025] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_forecast,
    ACTIONS(9), 1,
      anon_sym_driver,
    ACTIONS(11), 1,
      anon_sym_estimate,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    STATE(35), 5,
      sym__statement,
      sym_forecast_statement,
      sym_driver_statement,
      sym_estimate_statement,
      aux_sym_source_file_repeat1,
  [1048] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_forecast,
    ACTIONS(9), 1,
      anon_sym_driver,
    ACTIONS(11), 1,
      anon_sym_estimate,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    STATE(35), 5,
      sym__statement,
      sym_forecast_statement,
      sym_driver_statement,
      sym_estimate_statement,
      aux_sym_source_file_repeat1,
  [1071] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(98), 1,
      anon_sym_COMMA,
    ACTIONS(100), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1097] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(102), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1118] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(104), 1,
      anon_sym_COMMA,
    ACTIONS(106), 1,
      anon_sym_RPAREN,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1141] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1161] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1181] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1201] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1221] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1241] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(118), 1,
      anon_sym_RPAREN,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1261] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1281] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(122), 1,
      anon_sym_RPAREN,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1301] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1321] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(126), 1,
      anon_sym_COMMA,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1341] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(128), 1,
      anon_sym_COMMA,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1361] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1381] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_CARET,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1401] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1412] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1434] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1456] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1478] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 5,
      ts_builtin_sym_end,
      anon_sym_forecast,
      anon_sym_RBRACE,
      anon_sym_driver,
      anon_sym_estimate,
  [1522] = 5,
    ACTIONS(156), 1,
      anon_sym_DQUOTE,
    ACTIONS(158), 1,
      aux_sym_string_token1,
    ACTIONS(160), 1,
      anon_sym_BSLASH,
    ACTIONS(162), 1,
      sym_comment,
    STATE(68), 1,
      aux_sym_string_repeat1,
  [1538] = 5,
    ACTIONS(162), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_DQUOTE,
    ACTIONS(166), 1,
      aux_sym_string_token1,
    ACTIONS(169), 1,
      anon_sym_BSLASH,
    STATE(68), 1,
      aux_sym_string_repeat1,
  [1554] = 5,
    ACTIONS(160), 1,
      anon_sym_BSLASH,
    ACTIONS(162), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_DQUOTE,
    ACTIONS(174), 1,
      aux_sym_string_token1,
    STATE(67), 1,
      aux_sym_string_repeat1,
  [1570] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_function_call_repeat1,
  [1583] = 2,
    ACTIONS(162), 1,
      sym_comment,
    ACTIONS(164), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [1592] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_function_call_repeat1,
  [1605] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    STATE(74), 1,
      sym_string,
  [1615] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
    STATE(62), 1,
      sym_block,
  [1625] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_identifier,
  [1632] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LPAREN,
  [1639] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_LPAREN,
  [1646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
  [1653] = 2,
    ACTIONS(162), 1,
      sym_comment,
    ACTIONS(195), 1,
      aux_sym_string_token2,
  [1660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
  [1667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_LPAREN,
  [1674] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
  [1681] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
  [1688] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 69,
  [SMALL_STATE(5)] = 102,
  [SMALL_STATE(6)] = 135,
  [SMALL_STATE(7)] = 168,
  [SMALL_STATE(8)] = 201,
  [SMALL_STATE(9)] = 234,
  [SMALL_STATE(10)] = 267,
  [SMALL_STATE(11)] = 300,
  [SMALL_STATE(12)] = 333,
  [SMALL_STATE(13)] = 366,
  [SMALL_STATE(14)] = 389,
  [SMALL_STATE(15)] = 422,
  [SMALL_STATE(16)] = 455,
  [SMALL_STATE(17)] = 488,
  [SMALL_STATE(18)] = 521,
  [SMALL_STATE(19)] = 554,
  [SMALL_STATE(20)] = 587,
  [SMALL_STATE(21)] = 620,
  [SMALL_STATE(22)] = 653,
  [SMALL_STATE(23)] = 686,
  [SMALL_STATE(24)] = 719,
  [SMALL_STATE(25)] = 739,
  [SMALL_STATE(26)] = 759,
  [SMALL_STATE(27)] = 783,
  [SMALL_STATE(28)] = 805,
  [SMALL_STATE(29)] = 825,
  [SMALL_STATE(30)] = 845,
  [SMALL_STATE(31)] = 865,
  [SMALL_STATE(32)] = 885,
  [SMALL_STATE(33)] = 905,
  [SMALL_STATE(34)] = 925,
  [SMALL_STATE(35)] = 954,
  [SMALL_STATE(36)] = 978,
  [SMALL_STATE(37)] = 1002,
  [SMALL_STATE(38)] = 1025,
  [SMALL_STATE(39)] = 1048,
  [SMALL_STATE(40)] = 1071,
  [SMALL_STATE(41)] = 1097,
  [SMALL_STATE(42)] = 1118,
  [SMALL_STATE(43)] = 1141,
  [SMALL_STATE(44)] = 1161,
  [SMALL_STATE(45)] = 1181,
  [SMALL_STATE(46)] = 1201,
  [SMALL_STATE(47)] = 1221,
  [SMALL_STATE(48)] = 1241,
  [SMALL_STATE(49)] = 1261,
  [SMALL_STATE(50)] = 1281,
  [SMALL_STATE(51)] = 1301,
  [SMALL_STATE(52)] = 1321,
  [SMALL_STATE(53)] = 1341,
  [SMALL_STATE(54)] = 1361,
  [SMALL_STATE(55)] = 1381,
  [SMALL_STATE(56)] = 1401,
  [SMALL_STATE(57)] = 1412,
  [SMALL_STATE(58)] = 1423,
  [SMALL_STATE(59)] = 1434,
  [SMALL_STATE(60)] = 1445,
  [SMALL_STATE(61)] = 1456,
  [SMALL_STATE(62)] = 1467,
  [SMALL_STATE(63)] = 1478,
  [SMALL_STATE(64)] = 1489,
  [SMALL_STATE(65)] = 1500,
  [SMALL_STATE(66)] = 1511,
  [SMALL_STATE(67)] = 1522,
  [SMALL_STATE(68)] = 1538,
  [SMALL_STATE(69)] = 1554,
  [SMALL_STATE(70)] = 1570,
  [SMALL_STATE(71)] = 1583,
  [SMALL_STATE(72)] = 1592,
  [SMALL_STATE(73)] = 1605,
  [SMALL_STATE(74)] = 1615,
  [SMALL_STATE(75)] = 1625,
  [SMALL_STATE(76)] = 1632,
  [SMALL_STATE(77)] = 1639,
  [SMALL_STATE(78)] = 1646,
  [SMALL_STATE(79)] = 1653,
  [SMALL_STATE(80)] = 1660,
  [SMALL_STATE(81)] = 1667,
  [SMALL_STATE(82)] = 1674,
  [SMALL_STATE(83)] = 1681,
  [SMALL_STATE(84)] = 1688,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 7),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 7),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 9),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 9),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 6),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 6),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 5),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 5),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 4),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 4),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_probability, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_probability, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_estimate_statement, 2, 0, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 8),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_normal_distribution, 6, 0, 11),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_beta_distribution, 10, 0, 16),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_triangular_distribution, 8, 0, 15),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_distribution, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_driver_statement, 3, 0, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forecast_statement, 3, 0, 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_beta_distribution, 6, 0, 14),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uniform_distribution, 6, 0, 13),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lognormal_distribution, 6, 0, 12),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [169] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 10), SHIFT_REPEAT(18),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 10),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [201] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fpl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
