name = "FPL"
grammar = "fpl"
path_suffixes = ["fpl"]
line_comments = ["// "]
block_comment = ["/* ", " */"]

[brackets]
"(" = ")"
"{" = "}"
"[" = "]"
"\"" = "\""

[autoclose_before]
line_breaks = true

[code_actions_on_format]

[overrides]
