[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""
# Temporarily disable healthcheck to allow full initialization
# healthcheckPath = "/debug/healthz"
# healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
# Trigger redeploy - database cleaned
