#!/usr/bin/env python3
"""Emit the agent-scoped Loop 5 MECHANISM checks as PREPARE statements.

Reads `ROSTER_PREDICATE` and `LOOP5_AGENT_CHECKS` out of
`src/handlers/observatory.rs` and performs the same `{ROSTER}` substitution the
Rust does at runtime. The point of extracting rather than retyping: a hand-copied
SQL file would be a fourth copy of these checks and would validate itself instead
of the code that actually runs.

Output goes to stdout, wrapped in a transaction that always rolls back.
"""

import re
import sys
from pathlib import Path

SRC = Path("src/handlers/observatory.rs")


def rust_string_after(src: str, anchor: str) -> str:
    """The first plain `"..."` literal that *starts after* `anchor` ends.

    Searching from `index(anchor)` rather than from the end of the anchor finds
    the anchor's own opening quote when the anchor is itself a string literal --
    which silently yielded the severity ("CRITICAL") in place of every SQL body.
    """
    i = src.index(anchor) + len(anchor)
    start = src.index('"', i) + 1
    out, j = [], start
    while True:
        c = src[j]
        if c == "\\":
            nxt = src[j + 1]
            out.append({"n": "\n", "t": "\t", '"': '"', "\\": "\\"}.get(nxt, nxt))
            j += 2
            continue
        if c == '"':
            break
        out.append(c)
        j += 1
    return "".join(out)


def main() -> int:
    if not SRC.exists():
        print(f"FAIL: {SRC} not found (run from the repo root)", file=sys.stderr)
        return 1
    src = SRC.read_text()

    roster = rust_string_after(src, "const ROSTER_PREDICATE: &str =")

    block_start = src.index("const LOOP5_AGENT_CHECKS: &[AgentCheck] = &[")
    block_end = src.index("\n];", block_start)
    block = src[block_start:block_end]

    # Strip `//` line comments FIRST. Several entries carry an explanatory
    # comment between the severity and the SQL, and L5-M05's contains a
    # double-quoted phrase -- which the literal reader below happily returned as
    # the query body, producing `PREPARE ... AS did the emitter run for this`.
    # Safe blanket removal: SQL has no `//` operator, so no comment marker can
    # occur inside a query string in this table.
    block = re.sub(r"^\s*//[^\n]*\n", "", block, flags=re.M)

    # Each entry is ("L5-Mxx", "SEVERITY", "<sql>").
    entries = re.findall(
        r'\(\s*"(L5-M\d+)"\s*,\s*"([A-Z]+)"\s*,\s*(?://[^\n]*\n\s*)*"',
        block,
    )
    # Re-walk to pull each SQL body with the escape-aware reader.
    sqls, cursor = [], 0
    for check_id, severity in entries:
        idx = block.index(f'"{check_id}"', cursor)
        sql = rust_string_after(block[idx:], f'"{severity}"')
        sqls.append((check_id, severity, sql))
        cursor = idx + 1

    if not sqls:
        print("FAIL: extracted no checks — did the table format change?", file=sys.stderr)
        return 1

    print("-- GENERATED by scripts/emit_loop5_agent_sql.py — do not edit.")
    print("-- Source of truth: LOOP5_AGENT_CHECKS in src/handlers/observatory.rs")
    print("\\timing off")
    print("BEGIN;")
    for check_id, severity, sql in sqls:
        resolved = sql.replace("{ROSTER}", roster)
        if "{" in resolved and re.search(r"\{[A-Z]", resolved):
            print(f"FAIL: {check_id} has an unsubstituted placeholder", file=sys.stderr)
            return 1
        name = check_id.replace("-", "_").lower()
        print()
        print(f"\\echo '{check_id} ({severity})'")
        print(f"PREPARE {name} (uuid) AS")
        print(resolved.rstrip().rstrip(";"))
        print(";")
        print(f"DEALLOCATE {name};")
    print()
    print("ROLLBACK;")
    print(f"\\echo '{len(sqls)} agent-scoped checks validated.'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
