//! Agent taxonomy — derived ranks (SPEC_30).
//!
//! # Why this exists in Rust as well as Python
//!
//! `scripts/taxonomy.py` is the editorial tool: it audits the on-disk
//! `agent_card.json` corpus and helps a human fill the ranks that need a
//! human. But taxonomy previously lived *only* in those files, which meant
//! every agent created through the UI or the import endpoint could never be
//! classified at all — no card on disk, nothing to read. All 13 efra agents
//! sat under `Incertae sedis` permanently, and that is the majority shape
//! of third-party agents.
//!
//! So the derived ranks are computed here too, at creation time, writing
//! into `agents.taxonomy` (mig-186). An agent authored through the API is
//! classified the moment it exists.
//!
//! # The drift hazard, and what guards it
//!
//! Two implementations of one rule will diverge. That is not a hypothetical
//! — this codebase has already been bitten by a duplicated predicate
//! (`test_agent_` filtering was inline in several handlers and missing from
//! others, so the Observatory opened on a wall of test rows).
//!
//! The guard is `tests/taxonomy_parity.rs`, which reads
//! `agents/taxonomy_derived_expected.json` — regenerated by the Python tool
//! — and asserts this module produces identical output for every card in
//! the corpus. If either side changes a rule, the test fails.
//!
//! Editorial ranks (kingdom, family, genus) are deliberately absent. A name
//! is a claim about kinship; deriving one would be guessing convincingly.

use serde_json::{json, Value};

/// The seven ranks, in canonical order.
pub const RANKS: [&str; 7] = [
    "kingdom", "phylum", "class", "order", "family", "genus", "species",
];

/// Ranks this module can compute from the agent itself.
pub const DERIVED: [&str; 4] = ["phylum", "class", "order", "species"];

/// Ranks that require a human, drawn from `agents/taxonomy_vocab.json`.
pub const EDITORIAL: [&str; 3] = ["kingdom", "family", "genus"];

/// `class` ← `agent_type`, one-to-one. Keeps the rank verifiable: a card
/// whose stated class disagrees with its type is a detectable defect
/// rather than a matter of taste.
pub fn class_for(agent_type: &str) -> Option<&'static str> {
    Some(match agent_type.to_ascii_lowercase().as_str() {
        "research" => "Researchia",
        "creative" => "Creativia",
        "meta" => "Metaria",
        "observability" => "Vigilia",
        "coherence" => "Cohaerentia",
        "commerce" => "Mercatia",
        "strategist" => "Strategia",
        "compound" => "Compositia",
        "coordination" => "Coordinia",
        "game" => "Ludia",
        "companion" => "Compandia",
        "analytics" => "Analytia",
        "forecast" => "Prognostia",
        _ => return None,
    })
}

/// `order` ← output modality, matched by substring against the agent's
/// declared `produces`.
///
/// Deliberately NOT an enumeration of `produces` values. That field is free
/// text — 267 distinct values across 321 declarations in the curated
/// corpus, 234 of them appearing exactly once. Enumerating it would break
/// on every new card, and it is almost certainly the origin of the original
/// defect: `order` had 31 singletons across 37 values because it inherited
/// the pathology of the field it was derived from.
///
/// Evaluated in order — earlier entries win, so specific modalities are
/// tested before general ones and `Evidentiales` (the broadest) is last.
const ORDER_PATTERNS: &[(&str, &[&str])] = &[
    (
        "Prognosticales",
        &[
            "forecast",
            "predict",
            "projection",
            "estimate",
            "probabilit",
            "multiplier",
            "scenario",
            "outlook",
            "base_rate",
            "base-rate",
        ],
    ),
    (
        "Diagnosticales",
        &[
            "diagnos",
            "anomal",
            "alert",
            "flag",
            "warning",
            "risk",
            "health",
            "verdict",
            "incident",
            "conservation",
            "score",
        ],
    ),
    (
        "Consiliales",
        &[
            "recommend",
            "plan",
            "advice",
            "advisor",
            "strateg",
            "guide",
            "suggestion",
            "proposal",
            "ranking",
            "formulation",
        ],
    ),
    (
        "Imaginales",
        &[
            "image",
            "avatar",
            "scene",
            "render",
            "art",
            "visual",
            "media",
            "video",
            "audio",
            "voice",
            "placement",
            "choreograph",
        ],
    ),
    (
        "Narrativales",
        &[
            "narrat", "story", "post", "synopsis", "prose", "dream", "message", "response",
            "summary", "brief", "note",
        ],
    ),
    (
        "Operationales",
        &[
            "state",
            "config",
            "transform",
            "input",
            "action",
            "command",
            "operation",
            "task",
            "workflow",
            "packaged",
            "payload",
            "schema",
            "manifest",
            "rules",
            "ontolog",
            "embedding",
            "routing",
            "listing",
            "match",
            // Plural on purpose. Singular "position" also means an argued
            // stance (vote_strategist's `aggregate-position`), which is a
            // judgement rather than plumbing — matching it here filed a
            // consensus strategist under Operationales. The plural is the
            // spatial sense this was added for (`updated_positions`).
            "positions",
            "metric",
        ],
    ),
    (
        "Evidentiales",
        &[
            "evidence",
            "analys",
            "assess",
            "report",
            "profile",
            "finding",
            "research",
            "rating",
            "comparison",
            "audit",
            "scan",
            "intel",
            "catalog",
            "fact",
        ],
    ),
];

pub fn order_for(produces: &[String]) -> Option<&'static str> {
    if produces.is_empty() {
        // Nothing declared, so nothing to derive from. An authoring gap in
        // the card, not a taxonomy defect — reported, never guessed.
        return None;
    }
    let blob = produces.join(" ").to_ascii_lowercase();
    for (name, needles) in ORDER_PATTERNS {
        if needles.iter().any(|n| blob.contains(n)) {
            return Some(name);
        }
    }
    None
}

/// `phylum` ← mode of operation. Three values, so the rank actually
/// partitions the population instead of naming each member.
pub fn phylum_for(has_required_deps: bool, has_instruments: bool) -> &'static str {
    if has_required_deps {
        "Composita" // orchestrates other agents
    } else if has_instruments {
        "Instrumenta" // reaches for external tools / MCP servers / skills
    } else {
        "Solitaria" // works from its own prompt alone
    }
}

/// Inputs for derivation, so callers with different shapes (an `AgentCard`,
/// a DB row, a raw import payload) can all reach the same rules.
#[derive(Debug, Default, Clone)]
pub struct DeriveInput {
    pub agent_name: String,
    pub agent_type: String,
    pub produces: Vec<String>,
    pub has_required_deps: bool,
    pub has_instruments: bool,
}

/// Compute the derived ranks. Never returns editorial ranks, and omits any
/// rank it cannot determine rather than inventing a value.
pub fn derive(input: &DeriveInput) -> Value {
    let mut out = serde_json::Map::new();
    out.insert(
        "phylum".into(),
        json!(phylum_for(input.has_required_deps, input.has_instruments)),
    );
    if let Some(c) = class_for(&input.agent_type) {
        out.insert("class".into(), json!(c));
    }
    if let Some(o) = order_for(&input.produces) {
        out.insert("order".into(), json!(o));
    }
    out.insert("species".into(), json!(input.agent_name));
    Value::Object(out)
}

/// Merge derived ranks over whatever is already stored, preserving the
/// editorial ranks.
///
/// Derived ranks always win: they are computed from the agent, so a stored
/// value that disagrees is stale or wrong.
///
/// No attempt is made to order the keys. Two reasons, and the first is the
/// binding one: **Postgres JSONB does not preserve key order** — it stores
/// object keys sorted and deduplicated, so any ordering applied here is
/// discarded on write. (`serde_json::Map` is also a `BTreeMap` unless the
/// `preserve_order` feature is on, so it was alphabetical before it ever
/// reached the database.) Canonical rank ordering matters only for the
/// on-disk cards, where diff readability is real, and that is
/// `scripts/taxonomy.py`'s job — it writes the block as text.
pub fn merge(existing: Option<&Value>, derived: &Value) -> Value {
    let mut merged = serde_json::Map::new();
    if let Some(Value::Object(e)) = existing {
        for (k, v) in e {
            merged.insert(k.clone(), v.clone());
        }
    }
    if let Value::Object(d) = derived {
        for (k, v) in d {
            merged.insert(k.clone(), v.clone());
        }
    }
    Value::Object(merged)
}

/// Pull derivation inputs out of a parsed `agent_card.json`-shaped value.
pub fn input_from_card(card: &Value) -> DeriveInput {
    let caps = card.get("capabilities");
    let arr_len = |v: Option<&Value>| v.and_then(|x| x.as_array()).map_or(0, |a| a.len());
    DeriveInput {
        agent_name: card
            .get("agent_id")
            .or_else(|| card.get("agent_name"))
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string(),
        agent_type: card
            .get("agent_type")
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string(),
        produces: card
            .get("produces")
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str().map(String::from))
                    .collect()
            })
            .unwrap_or_default(),
        has_required_deps: arr_len(card.get("dependencies").and_then(|d| d.get("required"))) > 0,
        has_instruments: arr_len(caps.and_then(|c| c.get("mcp_servers"))) > 0
            || arr_len(caps.and_then(|c| c.get("mcp_tools"))) > 0
            || arr_len(caps.and_then(|c| c.get("skills"))) > 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn inp(t: &str, produces: &[&str]) -> DeriveInput {
        DeriveInput {
            agent_name: "a".into(),
            agent_type: t.into(),
            produces: produces.iter().map(|s| s.to_string()).collect(),
            ..Default::default()
        }
    }

    #[test]
    fn phylum_partitions_into_three() {
        assert_eq!(phylum_for(true, true), "Composita", "deps win over tools");
        assert_eq!(phylum_for(false, true), "Instrumenta");
        assert_eq!(phylum_for(false, false), "Solitaria");
    }

    #[test]
    fn class_is_one_to_one_with_agent_type() {
        assert_eq!(class_for("research"), Some("Researchia"));
        assert_eq!(
            class_for("RESEARCH"),
            Some("Researchia"),
            "case-insensitive"
        );
        // An unknown type yields nothing rather than a made-up class. The
        // original defect was `class` values that corresponded to nothing.
        assert_eq!(class_for("wat"), None);
    }

    #[test]
    fn order_is_matched_most_specific_first() {
        // `forecast` (Prognosticales) is checked before `analysis`
        // (Evidentiales), so a forecaster is not filed as generic evidence.
        assert_eq!(
            order_for(&["forecast".into(), "analysis".into()]),
            Some("Prognosticales")
        );
        assert_eq!(order_for(&["evidence".into()]), Some("Evidentiales"));
        assert_eq!(
            order_for(&["coherence-scores".into()]),
            Some("Diagnosticales")
        );
        // `narrat` catches `narration` as well as `narrative` — the gap that
        // left reynolds_flock unclassified.
        assert_eq!(
            order_for(&["movement_narration".into()]),
            Some("Narrativales")
        );
        assert_eq!(
            order_for(&["marketplace-listing".into()]),
            Some("Operationales")
        );
    }

    #[test]
    fn order_is_absent_when_nothing_is_declared() {
        // prey_locator declares `produces: null`. Deriving an order from no
        // outputs would be invention; absence is the honest answer.
        assert_eq!(order_for(&[]), None);
        let d = derive(&inp("research", &[]));
        assert!(d.get("order").is_none());
        assert_eq!(d.get("class").unwrap(), "Researchia");
    }

    #[test]
    fn derive_never_emits_editorial_ranks() {
        let d = derive(&inp("research", &["evidence".into()]));
        for rank in EDITORIAL {
            assert!(
                d.get(rank).is_none(),
                "{rank} is a claim about kinship and must never be auto-assigned"
            );
        }
    }

    #[test]
    fn merge_preserves_editorial_and_overwrites_stale_derived() {
        let existing = json!({
            "kingdom": "Quantitativa",
            "family": "Investigatidae",
            "genus": "Analyticus",
            "class": "Domainria",       // stale: predates the SPEC_30 reform
        });
        let derived = derive(&DeriveInput {
            agent_name: "macro_forecaster".into(),
            agent_type: "research".into(),
            produces: vec!["forecast".into()],
            has_instruments: true,
            ..Default::default()
        });
        let m = merge(Some(&existing), &derived);

        assert_eq!(m["kingdom"], "Quantitativa", "editorial preserved");
        assert_eq!(m["family"], "Investigatidae");
        assert_eq!(m["genus"], "Analyticus");
        assert_eq!(m["class"], "Researchia", "derived overwrites stale");
        assert_eq!(m["phylum"], "Instrumenta");
        assert_eq!(m["species"], "macro_forecaster");

        // Assert the key SET, not the order. Postgres JSONB sorts object
        // keys on write, so asserting an order here would be testing
        // something the database is about to discard. Rank ordering is only
        // meaningful for the on-disk cards, and taxonomy.py owns that.
        let mut keys: Vec<&str> = m.as_object().unwrap().keys().map(|s| s.as_str()).collect();
        keys.sort_unstable();
        let mut expected = vec![
            "kingdom", "phylum", "class", "order", "family", "genus", "species",
        ];
        expected.sort_unstable();
        assert_eq!(keys, expected, "all seven ranks present after merge");
    }

    #[test]
    fn input_from_card_reads_the_real_card_shape() {
        let card = json!({
            "agent_id": "x", "agent_type": "creative",
            "produces": ["image"],
            "dependencies": { "required": ["helper"], "optional": [] },
            "capabilities": { "skills": ["draw"] }
        });
        let i = input_from_card(&card);
        assert_eq!(i.agent_name, "x");
        assert!(i.has_required_deps);
        assert!(i.has_instruments);
        let d = derive(&i);
        assert_eq!(d["phylum"], "Composita");
        assert_eq!(d["class"], "Creativia");
        assert_eq!(d["order"], "Imaginales");
    }
}
